swagger: '2.0'
info:
  title: Zktoro Webhook Specification
  description: |
    Zktoro Webhook Specification
    Alert models are based on definitions in https://zktoro-alerts-api.
  version: 1.0.0
basePath: /zktoro/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /alerts:
    post:
      operationId: SendAlerts
      summary: Send a list of alerts
      parameters:
        - in: header
          name: Authorization
          description: Webhook request authorization
          type: string
        - in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/AlertBatch'
      responses:
        200:
          description: Successfully sent alerts
        400:
          $ref: '#/responses/BadRequestResponse'
        500:
          description: Internal error
        502:
          description: Bad gateway

responses:
  BadRequestResponse:
    description: Bad request
    schema:
      type: object
      properties:
        reason:
          type: string

definitions:
  AlertBatch:
    type: object
    properties:
      alerts:
        $ref: '#/definitions/AlertList'
      metrics:
        $ref: '#/definitions/BotMetricsList'

  AlertList:
    type: array
    items:
      $ref: '#/definitions/Alert'

  Alert:
    type: object
    properties:
      hash:
        type: string
        description: Deterministic alert hash
        example: '0xe9cfda18f167de5cdd63c101e38ec0d4cb0a1c2dea80921ecc4405c2b010855f'
      createdAt:
        type: string
        description: Timestamp (RFC3339Nano)
        example: '2022-03-01T12:24:33.379756298Z'
      alertId:
        type: string
        example: OZ-GNOSIS-EVENTS
      name:
        type: string
        example: Transfer Event
      protocol:
        type: string
        example: ethereum
      description:
        type: string
        example: Detected Transfer event
      findingType:
        type: string
        enum:
          - UNKNOWN_TYPE
          - EXPLOIT
          - SUSPICIOUS
          - DEGRADED
          - INFORMATION
          - SCAM
      severity:
        type: string
        enum:
          - UNKNOWN
          - INFO
          - LOW
          - MEDIUM
          - HIGH
          - CRITICAL
      metadata:
        type: object
        description: An associative array of string values
        example:
          contractAddress: '0x98883145049dec03c00cb7708cbc938058802520'
          operator: '0x1fFa3471A45C22B1284fE5a251eD74F40580a1E3'
      links:
        type: object
        description: An associative array of extra links values
        example:
          explorerUrl: 'https://explorer.zktoro.network/alert/0xd795c365931762afeccf4a440ecee2f7e89820c59136aa46310a8eec54ba96d8'
          blockUrl: 'https://etherscan.io/block/18646150'
      source:
        $ref: '#/definitions/AlertSource'
      addresses:
        type: array
        items:
          type: string
        description: Addresses involved in the source of this alert
        example:
          - '0x98883145049dec03c00cb7708cbc938058802520'
          - '0x1fFa3471A45C22B1284fE5a251eD74F40580a1E3'
      relatedAlerts:
        type: array
        items:
          type: string
        description: Related alerts involved in the source of this alert
        example:
          - '0xe9cfda18f167de5cdd63c101e38ec0d4cb0a1c2dea80921ecc4405c2b010855f'
          - '0x533c100d5d7a56ee8448b6b08b5b1ce41ea9d1667086e1d2d4c1f03d09d191b9'

  AlertSource:
    type: object
    properties:
      transactionHash:
        type: string
        example: '0x7040dd33cbfd3e9d880da80cb5f3697a717fc329abd0251f3dcd51599ab67b0a'
      bot:
        $ref: '#/definitions/AlertBot'
      block:
        $ref: '#/definitions/AlertBlock'
      sourceEvent:
        $ref: '#/definitions/AlertSourceEvent'

  AlertSourceEvent:
    type: object
    properties:
      botId:
        type: string
        example: '0x17381ae942ee1fe141d0652e9dad7d001761552f906fb1684b2812603de31049'
      alertHash:
        type: string
        description: Deterministic alert hash
        example: '0xe9cfda18f167de5cdd63c101e38ec0d4cb0a1c2dea80921ecc4405c2b010855f'

  AlertBot:
    type: object
    properties:
      id:
        type: string
        example: '0x17381ae942ee1fe141d0652e9dad7d001761552f906fb1684b2812603de31049'
      reference:
        type: string
        description: Bot reference (IPFS hash)
        example: QmU6L9Zo5rweF6QZLhLfwAAFUFRMF3uFdSnMiJzENXr37R
      image:
        type: string
        description: Docker image reference (Disco)
        example: bafybeibrigevnhic4befnkqbaagzgxqtdyv2fdgcbqwxe7ees3hw6fymme@sha256:9ca1547e130a6264bb1b4ad6b10f17cabf404957f23d457a30046b9afdf29fc8

  AlertBlock:
    type: object
    properties:
      number:
        type: integer
        format: uint64
        example: 1235678901234
      hash:
        type: string
        example: '0xf9e777b739cf90a197c74c461933422dcf26fadf50e0ef9aa72af76727da87ca'
      timestamp:
        type: string
        description: Timestamp (RFC3339)
        example: '2022-03-01T12:24:33Z'
      chainId:
        type: integer
        format: uint64
        example: 1337

  BotMetricsList:
    type: array
    items:
      $ref: '#/definitions/BotMetric'

  BotMetric:
    type: object
    properties:
      botId:
        type: string
        example: '0x17381ae942ee1fe141d0652e9dad7d001761552f906fb1684b2812603de31049'
      timestamp:
        type: string
        description: Timestamp (RFC3339Nano)
        example: '2022-03-01T12:24:33.379756298Z'
      metrics:
        type: array
        items:
          $ref: '#/definitions/BotMetricSummary'

  BotMetricSummary:
    type: object
    properties:
      name:
        type: string
        description: Metric name
        example: block.request
      count:
        type: number
        description: Total count of data points
        example: 1337
      max:
        type: number
        description: Max value from the data points
        example: 537
      average:
        type: number
        description: Average value of the data points
        example: 47
      sum:
        type: number
        description: Sum value of all data points
        example: 2157
      p95:
        type: number
        description: 95th percentile value of all data points
        example: 87
